stages:
  - server
  - frontend

backendtest:
  stage: server
  script:
    - cd server
  allow_failure: false
  tags:
    - centos

backendlint:
  stage: server
  script:
    - cd server
  allow_failure: false
  tags:
    - centos

frontendtest:
  stage: frontend
  script:
    - cd frontend
  allow_failure: false
  tags:
    - centos

frontendlint:
  stage: frontend
  script:
    - cd frontend
  allow_failure: false
  tags:
    - centos
