stages:
  - server
  - frontend

backendtest:
  stage: server
  script:
    - cd server
    - python3 -m coverage run --source="." manage.py test --noinput
    - python3 -m coverage report
  tags:
    - windows

backendlint:
  stage: server
  script:
    - cd server
    - pylint --rcfile=.pylintrc ./**/*.py || exit $((35 & $?))
  allow_failure: false
  tags:
    - windows

frontendtest:
  stage: frontend
  script:
    - cd frontend
    - npm run test
  allow_failure: false
  tags:
    - windows

frontendlint:
  stage: frontend
  script:
    - cd frontend
    - npm run eslint
    - npm run stylelint
  allow_failure: false
  tags:
    - windows
