# Generated by Django 2.1.4 on 2019-01-10 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListOfForbiddenStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=1000)),
                ('is_need_whiteboard', models.BooleanField()),
                ('is_need_code_editor', models.BooleanField()),
                ('is_need_password', models.BooleanField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.College')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAndStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.Room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAndTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_week', models.IntegerField()),
                ('class_day', models.IntegerField()),
                ('class_class', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.Room')),
            ],
        ),
        migrations.AddField(
            model_name='listofforbiddenstudents',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.Room'),
        ),
        migrations.AddField(
            model_name='listofforbiddenstudents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
